apiVersion: v1
kind: Service
metadata:
  name: ray-head-dashboard
  namespace: opencsg
spec:
  type: NodePort
  selector:
    ray.io/node-type: head
  ports:
  - protocol: TCP
    port: 8265
    targetPort: 8265
    nodePort: 31265
---
apiVersion: v1
kind: Service
metadata:
  name: ray-head-apiserver
  namespace: opencsg
spec:
  type: NodePort
  selector:
    ray.io/node-type: head
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31000