ray_serve_config: 
    import_path: aviary.frontend.app:app
    runtime_env:
        working_dir: .
        excludes: 
        - "deploy"
        - "aviary/backend"
        - "**.DS_Store"
        - ".git"
        env_vars:
          AVIARY_URL: "::param:aviary_url::"
          AVIARY_TOKEN: "::param:aviary_token::"
          AVIARY_FRONTEND_ONLY: "True"
    deployments:
    - name: AviaryFrontend
      ray_actor_options:
        num_cpus: 4.0
